version: "3.8"
services:
  # Postgres Database
  postgres:
    container_name: knighthack_dev_postgres_server
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - knighthack_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.staging

  # Django App
  backend:
    container_name: knighthack_dev_django_server
    build:
      context: .
      dockerfile: ./docker/django/development/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env.staging
    volumes:
      - ./backend:/backend
      - knighthack_media_volume:/media
    command: /start.sh
    depends_on:
      - postgres

  # celery:
  #   <<: *app
  #   container_name: celery
  #   depends_on:
  #     - db
  #     - redis
  #   ports: []
  #   command: /start-celery

  # celerybeat:
  #   <<: *app
  #   container_name: celerybeat
  #   depends_on:
  #     - db
  #     - redis
  #   ports: []
  #   command: /start-celerybeat

volumes:
  knighthack_data_dev:
  knighthack_media_volume:
